config/routes.rb
CmsApp::Application.routes.draw do
  resources :students

  resources :gebruikers

  resources :labos

  resources :studentens

  resources :users

  get "demo/index"

end

app/models/gebruiker.rb
class Gebruiker < ActiveRecord::Base
end

app/controllers/gebruikers_controller.rb
class GebruikersController < ApplicationController
  # GET /gebruikers
  # GET /gebruikers.xml
  def index
    @gebruikers = Gebruiker.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gebruikers }
    end
  end

  # GET /gebruikers/1
  # GET /gebruikers/1.xml
  def show
    @gebruiker = Gebruiker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gebruiker }
    end
  end

  # GET /gebruikers/new
  # GET /gebruikers/new.xml
  def new
    @gebruiker = Gebruiker.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gebruiker }
    end
  end

  # GET /gebruikers/1/edit
  def edit
    @gebruiker = Gebruiker.find(params[:id])
  end

  # POST /gebruikers
  # POST /gebruikers.xml
  def create
    @gebruiker = Gebruiker.new(params[:gebruiker])

    respond_to do |format|
      if @gebruiker.save
        format.html { redirect_to(@gebruiker, :notice => 'Gebruiker was successfully created.') }
        format.xml  { render :xml => @gebruiker, :status => :created, :location => @gebruiker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gebruiker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gebruikers/1
  # PUT /gebruikers/1.xml
  def update
    @gebruiker = Gebruiker.find(params[:id])

    respond_to do |format|
      if @gebruiker.update_attributes(params[:gebruiker])
        format.html { redirect_to(@gebruiker, :notice => 'Gebruiker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gebruiker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gebruikers/1
  # DELETE /gebruikers/1.xml
  def destroy
    @gebruiker = Gebruiker.find(params[:id])
    @gebruiker.destroy

    respond_to do |format|
      format.html { redirect_to(gebruikers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/gebruikers_helper.rb
module GebruikersHelper
end

app/views/gebruikers/_form.html.erb
<%= form_for(@gebruiker) do |f| %>
  <% if @gebruiker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gebruiker.errors.count, "error") %> prohibited this gebruiker from being saved:</h2>

      <ul>
      <% @gebruiker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gebruikers/edit.html.erb
<h1>Editing gebruiker</h1>

<%= render 'form' %>

<%= link_to 'Show', @gebruiker %> |
<%= link_to 'Back', gebruikers_path %>

app/views/gebruikers/index.html.erb
<h1>Listing gebruikers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gebruikers.each do |gebruiker| %>
  <tr>
    <td><%= link_to 'Show', gebruiker %></td>
    <td><%= link_to 'Edit', edit_gebruiker_path(gebruiker) %></td>
    <td><%= link_to 'Destroy', gebruiker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gebruiker', new_gebruiker_path %>

app/views/gebruikers/new.html.erb
<h1>New gebruiker</h1>

<%= render 'form' %>

<%= link_to 'Back', gebruikers_path %>

app/views/gebruikers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_gebruiker_path(@gebruiker) %> |
<%= link_to 'Back', gebruikers_path %>