config/routes.rb
CmsApp::Application.routes.draw do
  resources :students

  resources :gebruikers

  resources :labos

  resources :studentens

  resources :users

  get "demo/index"

end

app/models/labo.rb
class Labo < ActiveRecord::Base
end

app/controllers/labos_controller.rb
class LabosController < ApplicationController
  # GET /labos
  # GET /labos.xml
  def index
    @labos = Labo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @labos }
    end
  end

  # GET /labos/1
  # GET /labos/1.xml
  def show
    @labo = Labo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @labo }
    end
  end

  # GET /labos/new
  # GET /labos/new.xml
  def new
    @labo = Labo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @labo }
    end
  end

  # GET /labos/1/edit
  def edit
    @labo = Labo.find(params[:id])
  end

  # POST /labos
  # POST /labos.xml
  def create
    @labo = Labo.new(params[:labo])

    respond_to do |format|
      if @labo.save
        format.html { redirect_to(@labo, :notice => 'Labo was successfully created.') }
        format.xml  { render :xml => @labo, :status => :created, :location => @labo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @labo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /labos/1
  # PUT /labos/1.xml
  def update
    @labo = Labo.find(params[:id])

    respond_to do |format|
      if @labo.update_attributes(params[:labo])
        format.html { redirect_to(@labo, :notice => 'Labo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @labo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /labos/1
  # DELETE /labos/1.xml
  def destroy
    @labo = Labo.find(params[:id])
    @labo.destroy

    respond_to do |format|
      format.html { redirect_to(labos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/labos_helper.rb
module LabosHelper
end

app/views/labos/_form.html.erb
<%= form_for(@labo) do |f| %>
  <% if @labo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@labo.errors.count, "error") %> prohibited this labo from being saved:</h2>

      <ul>
      <% @labo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labos/edit.html.erb
<h1>Editing labo</h1>

<%= render 'form' %>

<%= link_to 'Show', @labo %> |
<%= link_to 'Back', labos_path %>

app/views/labos/index.html.erb
<h1>Listing labos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labos.each do |labo| %>
  <tr>
    <td><%= link_to 'Show', labo %></td>
    <td><%= link_to 'Edit', edit_labo_path(labo) %></td>
    <td><%= link_to 'Destroy', labo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Labo', new_labo_path %>

app/views/labos/new.html.erb
<h1>New labo</h1>

<%= render 'form' %>

<%= link_to 'Back', labos_path %>

app/views/labos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_labo_path(@labo) %> |
<%= link_to 'Back', labos_path %>